# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  # boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" ];
  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "usb_storage" "ums_realtek" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/028721e0-73df-4d2e-9a2e-a8fde121eb46";
      fsType = "ext4";
    };

  # P.S. The system will fail to boot if "tank" is not plugged in.
  fileSystems."/share" =
    { device = "tank";
      fsType = "zfs";
    };

  fileSystems."/butter" =
    { device = "/dev/disk/by-uuid/00b61609-2829-4f7a-b3ca-7c47aea77752";
      fsType = "btrfs";
    };

  swapDevices = [ { device = "/var/swapfile"; size = 2048; } ];

  nix.maxJobs = lib.mkDefault 2;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}

